FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    build-essential cmake g++ gcc gfortran \
    libopenmpi-dev openmpi-bin \
    python3 python3-pip python3-venv git wget \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
COPY requirements.txt .
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --upgrade pip && pip install -r requirements.txt
ENV OMP_NUM_THREADS=6
ENV IN_DOCKER=1
CMD ["python3", "main.py"]
