--  Configuration for stellarorion_program_proc generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Stellarorion_Program_Proc_Config is
   pragma Pure;

   Crate_Version : constant String := "0.1.0-dev";
   Crate_Name : constant String := "stellarorion_program_proc";

   Alire_Host_OS : constant String := "macos";

   Alire_Host_Arch : constant String := "aarch64";

   Alire_Host_Distro : constant String := "homebrew";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Stellarorion_Program_Proc_Config;
