#!/usr/bin/env python3
"""
================================================================================
SCRIPT: plot_hiad_3d.py — Interactive 3D HIAD Surface-of-Revolution Viewer
================================================================================

AXIOMS:
  AXIOM 1: The SPARTA .surf file contains a 2D axisymmetric profile where
           column 1 is the axial coordinate (Z) and column 2 is the radial
           coordinate (R), both in meters.
           (from: SPARTA surface file format, HIAD_GeometryEngine.py L841-882)

  AXIOM 2: A surface of revolution is generated by rotating the 2D profile
           around the Z-axis at N_az equally-spaced azimuthal angles.
           (from: Rapisarda 2023, Sec 3.7 — axisymmetric HIAD geometry)

  AXIOM 3: The profile is an open curve (not closed loop) — the first point
           is near the nose tip (R~0) and the last point is at the aft end.
           (from: Python reference export, HIAD_GeometryEngine.py L841-882)

THEOREMS:
  THEOREM 1: For each profile point (z_i, r_i) and azimuthal angle theta_j,
             the 3D surface point is:
               x_ij = r_i * cos(theta_j)
               y_ij = r_i * sin(theta_j)
               z_ij = z_i
           This is the standard parametric form of a surface of revolution.
           (from: Differential Geometry, do Carmo 1976)

  THEOREM 2: The resulting mesh has dimensions (N_profile, N_az) and
             represents the complete exterior surface of the HIAD aeroshell.
           (from: THEOREM 1, construction)

APPLICATIONS:
  - Read SPARTA .surf file
  - Build surface-of-revolution mesh
  - Render interactive 3D plot with plotly
  - Export as self-contained HTML file

CITATIONS:
  [1] Rapisarda, S. (2023). "IRVE-3 Aerothermodynamic Reconstruction."
      Thesis, University of Rome — Sec 3.7, Appendix C.1.
  [2] SPARTA DSMC Solver — Surface file format documentation.
  [3] do Carmo, M.P. (1976). "Differential Geometry of Curves and Surfaces."

TIMING ANALYSIS:
  Estimated Processing Time: O(N * M) where N=profile pts, M=azimuthal pts
  CPU Time: ~5ms for N=219, M=120
  WCET: ~50ms with large meshes
  Space Complexity: O(N * M) for the mesh arrays

================================================================================
"""

import json
import math
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
N_AZIMUTHAL = 120  # Number of azimuthal divisions (360/N_az degrees each)
OUTPUT_HTML = "HIAD_3D_model.html"


def read_surf(path: str) -> list[tuple[float, float]]:
    """
    Read a SPARTA .surf file and return list of (Z_axial, R_radial) points.

    AXIOM 1: Format is "# header", "N points", "N lines", blank,
             "Points", blank, "ID X Y", ..., blank, "Lines", ...
    We only read the Points block. X=axial(Z), Y=radial(R).
    """
    points: list[tuple[float, float]] = []
    in_points = False
    with open(path, "r") as f:
        for line in f:
            stripped = line.strip()
            if stripped == "Points":
                in_points = True
                continue
            if in_points:
                if stripped == "" or stripped == "Lines":
                    if stripped == "Lines":
                        break
                    continue
                parts = stripped.split()
                if len(parts) >= 3:
                    try:
                        # ID X Y  →  (Z_axial, R_radial)
                        z_axial = float(parts[1])
                        r_radial = float(parts[2])
                        points.append((z_axial, r_radial))
                    except ValueError:
                        continue
    return points


def build_revolution_mesh(
    profile: list[tuple[float, float]], n_az: int
) -> tuple[list[list[float]], list[list[float]], list[list[float]]]:
    """
    Build a surface-of-revolution mesh from a 2D axisymmetric profile.

    THEOREM 1: x = r*cos(theta), y = r*sin(theta), z = z
    Returns (X, Y, Z) as 2D lists for plotly go.Surface.
    """
    X: list[list[float]] = []
    Y: list[list[float]] = []
    Z: list[list[float]] = []

    for j in range(n_az):
        theta = 2.0 * math.pi * j / n_az
        cos_t = math.cos(theta)
        sin_t = math.sin(theta)
        row_x: list[float] = []
        row_y: list[float] = []
        row_z: list[float] = []
        for z_axial, r_radial in profile:
            row_x.append(r_radial * cos_t)
            row_y.append(r_radial * sin_t)
            row_z.append(z_axial)
        X.append(row_x)
        Y.append(row_y)
        Z.append(row_z)

    return X, Y, Z


def generate_html(
    X: list[list[float]],
    Y: list[list[float]],
    Z: list[list[float]],
    profile: list[tuple[float, float]],
    output_path: str,
) -> None:
    """
    Generate a self-contained interactive 3D HTML file using plotly.js CDN.

    APPLICATION STEP 1: Serialize mesh data as JSON
    APPLICATION STEP 2: Build HTML with embedded plotly.js trace
    APPLICATION STEP 3: Write to file
    """
    # Compute bounds for annotation
    max_r = max(r for _, r in profile)
    max_z = max(z for z, _ in profile)
    min_z = min(z for z, _ in profile)

    # Section labels from Rapisarda geometry
    # Seg 1: Nose arc (z from nose_radius*(1-sin(gamma)) to nose_radius)
    # Seg 2: Windward straight
    # Seg 3: Toroid wrap
    # Seg 4: Flat back

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>StellarOrion HIAD 3D Model — Rapisarda 2023</title>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<style>
  body {{
    margin: 0; padding: 0;
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    background: #0a0a0f;
    color: #e0e0e0;
  }}
  #header {{
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
    padding: 16px 24px;
    border-bottom: 2px solid #0f3460;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }}
  #header h1 {{
    margin: 0;
    font-size: 1.4em;
    color: #e94560;
  }}
  #header .subtitle {{
    font-size: 0.85em;
    color: #8892b0;
  }}
  #plot {{ width: 100%; height: calc(100vh - 80px); }}
  #info {{
    position: absolute;
    bottom: 20px;
    left: 20px;
    background: rgba(15, 52, 96, 0.9);
    padding: 12px 16px;
    border-radius: 8px;
    font-size: 0.82em;
    line-height: 1.6;
    border: 1px solid #0f3460;
    max-width: 340px;
  }}
  #info .label {{ color: #e94560; font-weight: 600; }}
</style>
</head>
<body>
<div id="header">
  <div>
    <h1>StellarOrion HIAD 3D Model</h1>
    <div class="subtitle">Rapisarda (2023) Flat-Skin Profile — Surface of Revolution</div>
  </div>
  <div class="subtitle" style="text-align:right">
    IRVE-3 Baseline: D=3.0m, &theta;=60&deg;, r<sub>N</sub>=0.55m<br>
    6 toroids, r<sub>tor</sub>=0.135m
  </div>
</div>
<div id="plot"></div>
<div id="info">
  <span class="label">Profile Points:</span> {len(profile)}<br>
  <span class="label">Azimuthal Divisions:</span> {N_AZIMUTHAL}<br>
  <span class="label">Max Radius:</span> {max_r:.4f} m<br>
  <span class="label">Axial Length:</span> {max_z - min_z:.4f} m<br>
  <span class="label">Geometry:</span> 4-segment flat-skin<br>
  &nbsp;&nbsp;1. Nose arc (sphere)<br>
  &nbsp;&nbsp;2. Windward straight (cone)<br>
  &nbsp;&nbsp;3. Toroid wrap (circular arc)<br>
  &nbsp;&nbsp;4. Flat back (aft closure)<br>
  <br>
  <span class="label">Drag to rotate</span> &middot; <span class="label">Scroll to zoom</span>
</div>
<script>
const X = {json.dumps(X)};
const Y = {json.dumps(Y)};
const Z = {json.dumps(Z)};

const trace = {{
  type: 'surface',
  x: X,
  y: Y,
  z: Z,
  colorscale: [
    [0.0,  '#0f3460'],
    [0.25, '#16213e'],
    [0.5,  '#1a1a2e'],
    [0.75, '#e94560'],
    [1.0,  '#ff6b6b']
  ],
  opacity: 0.92,
  lighting: {{
    ambient: 0.4,
    diffuse: 0.7,
    specular: 0.5,
    roughness: 0.3,
    fresnel: 0.2
  }},
  lightposition: {{x: 1000, y: 1000, z: 2000}},
  contours: {{
    x: {{show: false}},
    y: {{show: false}},
    z: {{show: true, color: '#e94560', width: 1, highlightwidth: 1}}
  }},
  hovertemplate: 'X: %{{x:.4f}} m<br>Y: %{{y:.4f}} m<br>Z: %{{z:.4f}} m<extra></extra>'
}};

const layout = {{
  scene: {{
    xaxis: {{title: 'X [m]', gridcolor: '#1a1a2e', zerolinecolor: '#0f3460', color: '#8892b0', showbackground: true, backgroundcolor: '#0a0a0f'}},
    yaxis: {{title: 'Y [m]', gridcolor: '#1a1a2e', zerolinecolor: '#0f3460', color: '#8892b0', showbackground: true, backgroundcolor: '#0a0a0f'}},
    zaxis: {{title: 'Z (axial) [m]', gridcolor: '#1a1a2e', zerolinecolor: '#0f3460', color: '#8892b0', showbackground: true, backgroundcolor: '#0a0a0f'}},
    aspectratio: {{x: 1, y: 1, z: 1.2}},
    camera: {{
      eye: {{x: 1.8, y: 1.2, z: 0.8}},
      up: {{x: 0, y: 0, z: 1}}
    }},
    bgcolor: '#0a0a0f'
  }},
  paper_bgcolor: '#0a0a0f',
  margin: {{l: 0, r: 0, t: 0, b: 0}},
  showlegend: false
}};

Plotly.newPlot('plot', [trace], layout, {{responsive: true}});
</script>
</body>
</html>"""

    with open(output_path, "w") as f:
        f.write(html)


def main() -> int:
    """
    APPLICATION:
      1. Parse .surf file from command-line arg or default path
      2. Build surface-of-revolution mesh
      3. Generate interactive HTML
      4. Print summary

    Safety fallback (code-quality.md): If file not found, print error and exit 1.
    """
    # Determine input path
    if len(sys.argv) > 1:
        surf_path = sys.argv[1]
    else:
        # Default: look for HIAD_custom.surf in project root
        script_dir = Path(__file__).resolve().parent
        surf_path = str(script_dir.parent / "HIAD_custom.surf")

    # APPLICATION STEP 1: Read the .surf file (AXIOM 1)
    try:
        profile = read_surf(surf_path)
    except FileNotFoundError:
        print(f"ERROR: Surface file not found: {surf_path}", file=sys.stderr)
        return 1
    except (OSError, ValueError) as exc:
        print(f"ERROR: Failed to read {surf_path}: {exc}", file=sys.stderr)
        return 1

    if len(profile) < 3:
        print(
            f"ERROR: Profile has only {len(profile)} points (need >= 3)",
            file=sys.stderr,
        )
        return 1

    print(f"Read {len(profile)} profile points from {surf_path}")
    print(f"  Axial range: {min(z for z, _ in profile):.6f} to "
          f"{max(z for z, _ in profile):.6f} m")
    print(f"  Radial range: {min(r for _, r in profile):.6f} to "
          f"{max(r for _, r in profile):.6f} m")

    # APPLICATION STEP 2: Build surface-of-revolution mesh (THEOREM 1)
    X, Y, Z = build_revolution_mesh(profile, N_AZIMUTHAL)
    print(f"Built revolution mesh: {N_AZIMUTHAL} x {len(profile)} = "
          f"{N_AZIMUTHAL * len(profile)} surface elements")

    # APPLICATION STEP 3: Generate interactive HTML
    output_path = str(Path(surf_path).parent / OUTPUT_HTML)
    generate_html(X, Y, Z, profile, output_path)
    print(f"\n3D model written to: {output_path}")
    print("Open in a browser to inspect the HIAD surface of revolution.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
